# This file is auto-generated by the script generate_translation_profile.py
# Do not edit this file manually

FORMS =	../../gui/dlg_settings.ui

SOURCES =	../../gui/dlg_settings.py \
	../../plugin_main.py \
	../../processing/provider.py \
	../../toolbelt/env_var_parser.py \
	../../toolbelt/log_handler.py \
	../../toolbelt/preferences.py

TRANSLATIONS = geoserver_manager_en.ts
