# This file is auto-generated by the script generate_translation_profile.py
# Do not edit this file manually

FORMS =	../../gui/dlg_main.ui \
	../../gui/dlg_settings.ui

SOURCES =	../../gui/dlg_main.py \
	../../gui/dlg_resource_form.py \
	../../gui/dlg_settings.py \
	../../gui/tab_datastores.py \
	../../gui/tab_workspaces.py \
	../../plugin_main.py \
	../../toolbelt/dependencies.py \
	../../toolbelt/env_var_parser.py \
	../../toolbelt/log_handler.py \
	../../toolbelt/preferences.py

TRANSLATIONS =	geoserver_manager_en.ts
