blank_issues_enabled: true

contact_links:
  - name: Documentation
    url: http://github.com/ronitjadhav/geoserver_manager/pages
    about: Please read carefully the documentation before to submit an issue.
