#!python3

"""Configuration for project documentation using Sphinx."""

# standard
import json
import logging
import sys
from datetime import datetime
from pathlib import Path
from typing import Optional, Union

# 3rd party
import keepachangelog

# move into project package
sys.path.insert(0, f"{Path(__file__).parent.parent.resolve()}")

# Package
from geoserver_manager import __about__

# -- Logging setup --
logger: logging.Logger = logging.getLogger(__name__)

# -- Project information --
changes: dict[str, dict] = keepachangelog.to_dict("../CHANGELOG.md")
latest_version: str = [
    v for v in changes.keys() if v not in ("Unreleased", "version_tag")
][0]

author: str = __about__.__author__
copyright: str = __about__.__copyright__
description: str = __about__.__summary__
official_repository_id: Optional[int] = None
project: str = __about__.__title__
release: str = latest_version  # latest version from CHANGELOG.md
version: str = __about__.__version__  # defined in metadata.txt

# -- General configuration ---------------------------------------------------

# Add any Sphinx extension module names here, as strings. They can be
# extensions coming with Sphinx (named 'sphinx.ext.*') or your custom
# ones.
extensions: list[str] = [
    # Sphinx included
    "sphinx.ext.autosectionlabel",
    "sphinx.ext.extlinks",
    "sphinx.ext.githubpages",
    "sphinx.ext.intersphinx",
    "sphinx.ext.viewcode",
    # 3rd party
    "myst_parser",
    "sphinx_copybutton",
    "sphinx_rtd_theme",
]


# The suffix(es) of source filenames.
# You can specify multiple suffix as a list of string:
source_suffix: dict[str, str] = {".md": "markdown", ".rst": "restructuredtext"}
autosectionlabel_prefix_document: bool = True
# The master toctree document.
master_doc: str = "index"


# List of patterns, relative to source directory, that match files and
# directories to ignore when looking for source files.
# This pattern also affects html_static_path and html_extra_path .
exclude_patterns: list[str] = [
    "_build",
    ".venv",
    "Thumbs.db",
    ".DS_Store",
    "_output",
    "ext_libs",
    "tests",
    "demo",
    "_autogenerated"
]

# The name of the Pygments (syntax highlighting) style to use.
pygments_style: str = "sphinx"


# -- Options for HTML output -------------------------------------------------

# -- Theme

html_favicon: str = str(__about__.__icon_path__)
html_logo: str = str(__about__.__icon_path__)
# uncomment next line if you store some statics which are not directly linked into the markdown/RST files
# html_static_path = ["static/include_additional"]
html_theme = "sphinx_rtd_theme"
html_theme_options: dict[str, Union[bool, int, str]] = {
    "display_version": True,
    "logo_only": False,
    "prev_next_buttons_location": "both",
    "style_external_links": True,
    "style_nav_header_background": "SteelBlue",
    # Toc options
    "collapse_navigation": True,
    "includehidden": False,
    "navigation_depth": 4,
    "sticky_navigation": False,
    "titles_only": False,
}

# -- EXTENSIONS --------------------------------------------------------

# Configuration for intersphinx (refer to others docs).
intersphinx_mapping: dict[str, tuple[str, None]] = {
    "PyQt5": ("https://www.riverbankcomputing.com/static/Docs/PyQt5", None),
    "PyQt6": ("https://www.riverbankcomputing.com/static/Docs/PyQt6", None),
    "python": ("https://docs.python.org/3/", None),
    "qgis": ("https://qgis.org/pyqgis/master/", None),
}

# MyST Parser
myst_enable_extensions: list[str] = [
    "amsmath",
    "colon_fence",
    "deflist",
    "dollarmath",
    "html_image",
    "linkify",
    "replacements",
    "smartquotes",
    "substitution",
]

myst_substitutions: dict[str, str] = {
    "author": author,
    "date_update": datetime.now().strftime("%d %B %Y"),
    "description": description,
    "qgis_version_max": __about__.__plugin_md__.get("general").get(
        "qgismaximumversion"
    ),
    "qgis_version_min": __about__.__plugin_md__.get("general").get(
        "qgisminimumversion"
    ),
    "repo_url": __about__.__uri__,
    "title": project,
    "version": version,
    "release_version": release,
}

myst_url_scheme: tuple[str, str, str] = ("http", "https", "mailto")


# -- Hooks --
def generate_qdt_snippet(_) -> None:
    """Generate QDT snippet for profiles.json files."""
    logger.info("=== START GENERATING QDT SNIPPET ===")

    output_path: Path = Path("./docs/static/_autogenerated/qdt_snippet.json")
    output_path.parent.mkdir(parents=True, exist_ok=True)

    qdt_snippet: dict[str, Union[str, bool, int]] = {
        "name": "GeoServer Manager",
        "folder_name": "geoserver_manager",
        "official_repository": True,
        "plugin_id": official_repository_id,
        "version": f"{latest_version}",
    }

    with output_path.open("w", encoding="UTF8") as wf:
        wf.write(json.dumps(qdt_snippet, indent=4, sort_keys=True))


# launch setup
def setup(app) -> None:
    """Sphinx setup hook."""
    app.connect("builder-inited", generate_qdt_snippet)

